<?php

namespace App\Controller\Admin;

use App\Entity\Lesson;
use App\Entity\Module;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\DomCrawler\Field\FileFormField;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Security\Core\Security;

class LessonCrudController extends AbstractCrudController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public static function getEntityFqcn(): string
    {
        return Lesson::class;
    }

    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title', 'Titre'),
            TextField::new('goal', 'Objectif'),
            TextEditorField::new('content', 'Content'),
            AssociationField::new('id_module', 'Module')
        ];
    }

    public function createEntity(string $entityFqcn)
    {
        $lesson = new Lesson();

        $user = $this->security->getUser()->getTeacher();

        if ($user) {
            $lesson->setIdTeacher($user);
        }

        return $lesson; // TODO: Change the autogenerated stub
    }

}
