services:
  mariadb:
    image: mariadb:11.1.2
    restart: unless-stopped
    volumes:
      - ./infra/volumes/dev/database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025, 1080:1080 ]
