services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: challengeStack
      MYSQL_USER: esgi
      MYSQL_PASSWORD: password
    volumes:
      - mariadb_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mariadb
      PMA_USER: esgi
      PMA_PASSWORD: password
    ports:
      - "8080:80"

  mailcatcher:
    restart: on-failure
    image: schickling/mailcatcher
    ports: [ 1025:1025, 1080:1080 ]

volumes:
  mariadb_data:
